version: '3.9'

services:
  web:
    build: .
    command: gunicorn edutrack_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    volumes:
      - .:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
  
volumes:
  postgres-data:
    driver: local